name: 기능 개발
description: 기능 추가, 개선, 계획 등
title: "[Feature] 이슈 한줄 요약을 제목으로"
labels: []
assignees: []
type: Feature
body:
  - type: input
    id: summary
    attributes:
      label: "1. 한 줄 요약"
      description: "기능에 대한 한줄 요약"
      placeholder: "ex. 디바이스 소유권 변경 기능 추가"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: "2. 배경/문제"
      description: "왜 이 기능을 개발하는지"
      placeholder: |
        - 왜 필요한가:
        - 현재 불편/리스크/요구사항 변화:
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: "3. 요구 사항"
      description: "만족해야 하는 조건을 체크박스로 정리"
      placeholder: |
        - [ ] (필수) 관리자는 디바이스 소유권을 변경할 수 있어야 한다.
        - [ ] (필수) 관리자는 디바이스의 소유자를 알 수 있어야 한다.
        - [ ] (선택) 탈퇴한 회원에게 디바이스 소유권이 이전되지 않아야 한다.
        - [ ] 추가적인 요구사항...
        - [ ] (선택) (성능/응답시간/캐싱/동시성 요구)
        - [ ] (선택) (로깅/모니터링/알림)
        - [ ] (선택) 호환성(버전/마이그레이션/하위호환)
        - [ ] 등등..
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "4. 작업 항목"
      description: "작업 항목을 체크박스로 정리"
      placeholder: |
        - [ ] 디바이스 소유권 변경 UI 개발
        - [ ] 디바이스 소유권 변경 API 개발
        - [ ] 유닛 테스트
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: "5. 참고"
      placeholder: |
        - 관련 이슈/PR:
        - 레퍼런스 문서/스펙:
        - 스크린샷/로그:
    validations:
      required: false
