name: 버그 리포트
description: 버그 및 에러, 정상적이지 않은 동작
title: "[Bug] 문제가 요약된 제목"
labels: []
assignees: []
type: Bug
body:
  - type: input
    id: abstraction
    attributes:
      label: 증상 한 줄 요약
      description: 어떤 문제가 발생하는지 한 줄로 요약
      placeholder: ex. App status 변경 api 호출 시 status 가 변경되지 않는 현상
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: 기대 동작
      description: 정상이라면 어떻게 동작해야 하는지
      placeholder: ex. Admin 이 status 변경 API 호출 시 status 가 변경되어야 한다.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      description: 실제로는 어떻게 동작하는지
      placeholder: 에러 메시지/상태코드 등 구체적으로, 필요 시 스크린샷
    validations:
      required: true
  - type: textarea
    id: retry
    attributes:
      label: 재현 방법 (선택)
      description: 버그 재현 방법
      placeholder: |
        1)
        2)
        3)
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: 빈도
      description: 얼마나 자주 발생하나요?
      options:
        - 항상
        - 가끔
        - 특정 조건에서만
        - 재현 불가
    validations:
      required: true

  - type: dropdown
    id: user_impact
    attributes:
      label: 사용자 영향
      description: 영향도를 선택해주세요
      options:
        - 치명
        - 높음
        - 중간
        - 낮음
    validations:
      required: true

  - type: textarea
    id: resolution
    attributes:
      label: 해결 방법(초안)
      description: 해결 방법은 개략적으로 작성하고, 상세는 이슈 코멘트로 보충합니다.
      placeholder: |
        - 해결 방법 1:
        - 해결 방법 2:
    validations:
      required: false
